name: Build and test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    env:
      MalievWorkspaceRoot: ${{ github.workspace }}/.dependencies
    steps:
      - name: Check out NotificationService
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Check out Legacy.Maliev.ServiceDefaults
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          repository: MALIEV-Co-Ltd/Legacy.Maliev.ServiceDefaults
          ref: 7edcd961024868513fd5f373cab3dcb261197f77
          path: .dependencies/Legacy.Maliev.ServiceDefaults
          persist-credentials: false
      - name: Check out Legacy.Maliev.CompatibilityContracts
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          repository: MALIEV-Co-Ltd/Legacy.Maliev.CompatibilityContracts
          ref: 78e48ffc4ee000df0510cba5e7c7a3c4c4d539d7
          path: .dependencies/Legacy.Maliev.CompatibilityContracts
          persist-credentials: false
      - name: Validate .NET solution
        uses: MALIEV-Co-Ltd/Legacy.Maliev.Workflows/actions/dotnet-validate@73dd7304ffe85ec504389fd7664cc39070b9f148
        with:
          solution: Legacy.Maliev.NotificationService.slnx
          use-local-maliev-dependencies: 'true'
